module org.xmlobjects.gml {
    requires transitive org.xmlobjects;

    exports org.xmlobjects.gml.adapter;
    exports org.xmlobjects.gml.adapter.base;
    exports org.xmlobjects.gml.adapter.basictypes;
    exports org.xmlobjects.gml.adapter.coverage;
    exports org.xmlobjects.gml.adapter.deprecated;
    exports org.xmlobjects.gml.adapter.dictionary;
    exports org.xmlobjects.gml.adapter.feature;
    exports org.xmlobjects.gml.adapter.geometry;
    exports org.xmlobjects.gml.adapter.geometry.aggregates;
    exports org.xmlobjects.gml.adapter.geometry.compact;
    exports org.xmlobjects.gml.adapter.geometry.complexes;
    exports org.xmlobjects.gml.adapter.geometry.grids;
    exports org.xmlobjects.gml.adapter.geometry.primitives;
    exports org.xmlobjects.gml.adapter.measures;
    exports org.xmlobjects.gml.adapter.temporal;
    exports org.xmlobjects.gml.adapter.valueobjects;
    exports org.xmlobjects.gml.converter;
    exports org.xmlobjects.gml.model;
    exports org.xmlobjects.gml.model.base;
    exports org.xmlobjects.gml.model.basictypes;
    exports org.xmlobjects.gml.model.common;
    exports org.xmlobjects.gml.model.coverage;
    exports org.xmlobjects.gml.model.deprecated;
    exports org.xmlobjects.gml.model.dictionary;
    exports org.xmlobjects.gml.model.feature;
    exports org.xmlobjects.gml.model.geometry;
    exports org.xmlobjects.gml.model.geometry.aggregates;
    exports org.xmlobjects.gml.model.geometry.compact;
    exports org.xmlobjects.gml.model.geometry.complexes;
    exports org.xmlobjects.gml.model.geometry.grids;
    exports org.xmlobjects.gml.model.geometry.primitives;
    exports org.xmlobjects.gml.model.measures;
    exports org.xmlobjects.gml.model.temporal;
    exports org.xmlobjects.gml.model.valueobjects;
    exports org.xmlobjects.gml.model.xlink;
    exports org.xmlobjects.gml.util;
    exports org.xmlobjects.gml.util.id;
    exports org.xmlobjects.gml.util.matrix;
    exports org.xmlobjects.gml.util.reference;
    exports org.xmlobjects.gml.visitor;

    opens org.xmlobjects.gml.model to org.xmlobjects;
    opens org.xmlobjects.gml.model.base to org.xmlobjects;
    opens org.xmlobjects.gml.model.basictypes to org.xmlobjects;
    opens org.xmlobjects.gml.model.common to org.xmlobjects;
    opens org.xmlobjects.gml.model.coverage to org.xmlobjects;
    opens org.xmlobjects.gml.model.deprecated to org.xmlobjects;
    opens org.xmlobjects.gml.model.dictionary to org.xmlobjects;
    opens org.xmlobjects.gml.model.feature to org.xmlobjects;
    opens org.xmlobjects.gml.model.geometry to org.xmlobjects;
    opens org.xmlobjects.gml.model.geometry.aggregates to org.xmlobjects;
    opens org.xmlobjects.gml.model.geometry.compact to org.xmlobjects;
    opens org.xmlobjects.gml.model.geometry.complexes to org.xmlobjects;
    opens org.xmlobjects.gml.model.geometry.grids to org.xmlobjects;
    opens org.xmlobjects.gml.model.geometry.primitives to org.xmlobjects;
    opens org.xmlobjects.gml.model.measures to org.xmlobjects;
    opens org.xmlobjects.gml.model.temporal to org.xmlobjects;
    opens org.xmlobjects.gml.model.valueobjects to org.xmlobjects;
    opens org.xmlobjects.gml.model.xlink to org.xmlobjects;
}